import Footer from "@/components/Footer";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from 'next/font/local'


const sink = localFont({
	src: [
		{
			path: '../../../public/fonts/sink.otf',
			weight: '400'
		},
		{
			path: '../../../public/fonts/sink.otf',
			weight: '700'
		}
	],
	variable: '--font-sink',
})
const guzan = localFont({
	src: [
		{
			path: '../../../public/fonts/guzan.otf',
			weight: '400'
		},
		{
			path: '../../../public/fonts/guzan.otf',
			weight: '700'
		}
	],
	variable: '--font-guzan',
})

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "BrooCode",
	description: "Generated by create next app",
};
export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (

		<div
			className={`${geistSans.variable} ${geistMono.variable} ${sink.variable} ${guzan.variable} ${inter.variable} antialiased`}
		>
			{children}
			<Footer />
		</div>

	);
}
